name: waste_management_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase/supabase
  # firebase_analytics: ^11.3.0
  # firebase_core: ^3.14.0
  # firebase_auth: ^5.6.0
  # cloud_firestore: ^5.6.9
  # firebase_storage: ^12.3.3
  supabase_flutter: ^2.8.2

  # # Maps & Location
  # google_maps_flutter: ^2.9.0
  # google_maps_flutter_web: ^0.5.12
  # geolocator: ^14.0.1
  # location: ^8.0.0

  # State Management & Utilities
  provider: ^6.0.5
  get: ^4.6.6
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.20.2
  universal_io: ^2.2.2

  # UI & Design
  flutter_chat_core: ^2.6.1
  flutter_chat_ui: ^2.0.0
  flutter_rating_bar: ^4.0.1
  glassmorphism: ^3.0.0
  flutter_holo_date_picker: ^2.0.0
  cached_network_image: ^3.2.0
  google_fonts: ^6.2.1

  # Payments
  # flutter_stripe: ^11.5.0

  # Network & Media
  http: ^1.2.2
  image_picker: ^1.0.4
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
    
    


dependency_overrides:
  freezed_annotation: ^3.0.0 # Force this version
